name: Trigger Action on a CRON Schedule

on:
   workflow_dispatch:
#   schedule:
#     - cron: '16 19 * * *' # Runs at 12:30 AM IST every day

jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      

      - name: Run your code with secrets
        env:
          USERNAME: "abhishek"
         
        run: python count.py
